// GENERATED by scripts/gen-protocol-errors.mjs — do not edit by hand.
/**
 * Every custom error the contracts in the bots' call graph can revert with, as one flat ABI
 * fragment list.
 *
 * A revert is decoded against the ABI passed to the call that made it, and viem can only name an
 * error whose selector it finds there. That matters here because the contracts the bots call are
 * thin: `swapWbtcForVault` reverts from inside `ApplicationRegistry` or `BTCVaultRegistry` at
 * least as often as it does with one of `BTCVaultSwap`'s own errors. `UnauthorizedVaultKeeper()`
 * — what an unregistered keeper hits on its first acquisition — is declared in
 * `ApplicationRegistry`, so a per-contract ABI misses it and viem surfaces a bare `0xc2732b47`
 * that nothing downstream can classify.
 *
 * Hence a union rather than a per-contract list: it is spread into every ABI the bots call through,
 * so a selector decodes no matter which contract in the call graph raised it. Selectors are
 * globally unique across these contracts, which is what makes merging them into one list safe.
 *
 * `protocolErrors.test.ts` pins every entry back to the artifacts and re-checks that uniqueness,
 * so a contracts bump that renames or re-types an error fails there rather than degrading into an
 * undecodable selector at runtime.
 */
export const protocolErrorsAbi = [
  {
    type: "error",
    name: "AccessManagedInvalidAuthority",
    inputs: [{ name: "authority", type: "address" }],
  },
  {
    type: "error",
    name: "AccessManagedRequiredDelay",
    inputs: [
      { name: "caller", type: "address" },
      { name: "delay", type: "uint32" },
    ],
  },
  {
    type: "error",
    name: "AccessManagedUnauthorized",
    inputs: [{ name: "caller", type: "address" }],
  },
  { type: "error", name: "ActivationDeadlineExpired", inputs: [] },
  { type: "error", name: "ActivationDelayNotElapsed", inputs: [] },
  { type: "error", name: "AddressEmptyCode", inputs: [{ name: "target", type: "address" }] },
  {
    type: "error",
    name: "AmountMismatch",
    inputs: [
      { name: "expected", type: "uint256" },
      { name: "actual", type: "uint256" },
    ],
  },
  { type: "error", name: "ApplicationAlreadyRegistered", inputs: [] },
  { type: "error", name: "ApplicationNotActive", inputs: [] },
  { type: "error", name: "ApplicationNotRegistered", inputs: [] },
  { type: "error", name: "AssetNotListed", inputs: [] },
  {
    type: "error",
    name: "BelovedError",
    inputs: [
      { name: "netWbtcBeforePayment", type: "uint256" },
      {
        name: "debts",
        type: "tuple[]",
        components: [
          { name: "token", type: "address" },
          { name: "venue", type: "address" },
          { name: "amount", type: "uint256" },
        ],
      },
    ],
  },
  { type: "error", name: "BlocklistedVaultKeeper", inputs: [] },
  { type: "error", name: "BtcKeyAlreadyRegistered", inputs: [] },
  { type: "error", name: "BTCVaultNotFound", inputs: [] },
  { type: "error", name: "CannotReceiveShares", inputs: [] },
  { type: "error", name: "DeficitReportedMismatch", inputs: [] },
  { type: "error", name: "DelegateeNotVerified", inputs: [] },
  { type: "error", name: "DuplicateHashlock", inputs: [] },
  { type: "error", name: "DuplicateParticipant", inputs: [] },
  { type: "error", name: "DynamicConfigKeyUninitialized", inputs: [] },
  { type: "error", name: "ECDSAInvalidSignature", inputs: [] },
  {
    type: "error",
    name: "ECDSAInvalidSignatureLength",
    inputs: [{ name: "length", type: "uint256" }],
  },
  { type: "error", name: "ECDSAInvalidSignatureS", inputs: [{ name: "s", type: "bytes32" }] },
  { type: "error", name: "EmptyArray", inputs: [] },
  { type: "error", name: "EmptyPayoutAddress", inputs: [] },
  { type: "error", name: "EmptyVaultKeepers", inputs: [] },
  {
    type: "error",
    name: "ERC1967InvalidImplementation",
    inputs: [{ name: "implementation", type: "address" }],
  },
  { type: "error", name: "ERC1967NonPayable", inputs: [] },
  { type: "error", name: "EthKeyAlreadyRegistered", inputs: [] },
  { type: "error", name: "FailedCall", inputs: [] },
  { type: "error", name: "HealthFactorBelowThreshold", inputs: [] },
  { type: "error", name: "HealthFactorNotBelowThreshold", inputs: [] },
  {
    type: "error",
    name: "IncompleteWithdrawal",
    inputs: [
      { name: "expected", type: "uint256" },
      { name: "actual", type: "uint256" },
    ],
  },
  { type: "error", name: "InsufficientBorrowAllowance", inputs: [] },
  { type: "error", name: "InsufficientDeficitElimination", inputs: [] },
  { type: "error", name: "InsufficientFairnessDebtRepayment", inputs: [] },
  { type: "error", name: "InsufficientLiquidationOutput", inputs: [] },
  { type: "error", name: "InsufficientSettlementAmount", inputs: [] },
  {
    type: "error",
    name: "InvalidAccountNonce",
    inputs: [
      { name: "account", type: "address" },
      { name: "currentNonce", type: "uint256" },
    ],
  },
  { type: "error", name: "InvalidAddress", inputs: [] },
  { type: "error", name: "InvalidAmount", inputs: [] },
  { type: "error", name: "InvalidApplicationStatus", inputs: [] },
  { type: "error", name: "InvalidAssetDecimals", inputs: [] },
  { type: "error", name: "InvalidAssetId", inputs: [] },
  {
    type: "error",
    name: "InvalidBase",
    inputs: [
      { name: "base", type: "uint256" },
      { name: "modulus", type: "uint256" },
    ],
  },
  { type: "error", name: "InvalidBTCProofOfPossession", inputs: [] },
  { type: "error", name: "InvalidBTCPublicKey", inputs: [] },
  { type: "error", name: "InvalidBTCVaultStatus", inputs: [] },
  { type: "error", name: "InvalidBTCVaultUsageStatus", inputs: [] },
  { type: "error", name: "InvalidCollateralFactor", inputs: [] },
  { type: "error", name: "InvalidCollateralFactorAndMaxLiquidationBonus", inputs: [] },
  { type: "error", name: "InvalidCollateralRisk", inputs: [] },
  { type: "error", name: "InvalidDebtToCover", inputs: [] },
  { type: "error", name: "InvalidEscrowedVaultStatus", inputs: [] },
  { type: "error", name: "InvalidEthProofOfPossession", inputs: [] },
  { type: "error", name: "InvalidFeeConfiguration", inputs: [] },
  { type: "error", name: "InvalidHashlock", inputs: [] },
  { type: "error", name: "InvalidInitialization", inputs: [] },
  { type: "error", name: "InvalidLiquidationAmounts", inputs: [] },
  { type: "error", name: "InvalidLiquidationConfig", inputs: [] },
  { type: "error", name: "InvalidLiquidationFee", inputs: [] },
  { type: "error", name: "InvalidMaxUserReservesLimit", inputs: [] },
  { type: "error", name: "InvalidMinimumProfitThreshold", inputs: [] },
  { type: "error", name: "InvalidNumVaultsToLiquidate", inputs: [] },
  { type: "error", name: "InvalidOracleDecimals", inputs: [] },
  { type: "error", name: "InvalidOraclePrice", inputs: [] },
  {
    type: "error",
    name: "InvalidPeginFee",
    inputs: [
      { name: "provided", type: "uint256" },
      { name: "required", type: "uint256" },
    ],
  },
  {
    type: "error",
    name: "InvalidPoint",
    inputs: [
      { name: "x", type: "uint256" },
      { name: "y", type: "uint256" },
    ],
  },
  { type: "error", name: "InvalidPositionSizes", inputs: [] },
  { type: "error", name: "InvalidPriorityOrder", inputs: [] },
  { type: "error", name: "InvalidProxyContract", inputs: [] },
  { type: "error", name: "InvalidReceiver", inputs: [] },
  { type: "error", name: "InvalidSecret", inputs: [] },
  { type: "error", name: "InvalidShortString", inputs: [] },
  { type: "error", name: "InvalidSignature", inputs: [] },
  { type: "error", name: "InvalidVaultsArray", inputs: [] },
  { type: "error", name: "InvalidXOnlyKey", inputs: [{ name: "xOnly", type: "bytes32" }] },
  { type: "error", name: "LLPDisabled", inputs: [] },
  { type: "error", name: "MaxDataSizeExceeded", inputs: [] },
  { type: "error", name: "MaximumDynamicConfigKeyReached", inputs: [] },
  { type: "error", name: "MaximumUserReservesExceeded", inputs: [] },
  { type: "error", name: "MustNotLeaveDust", inputs: [] },
  { type: "error", name: "NoAccruedInterest", inputs: [] },
  { type: "error", name: "NonZeroLiquidationFee", inputs: [] },
  { type: "error", name: "NotInitializing", inputs: [] },
  { type: "error", name: "OnlyAdapter", inputs: [] },
  { type: "error", name: "OperationKeyVersionOverflow", inputs: [] },
  { type: "error", name: "PayoutAddressTooLong", inputs: [] },
  { type: "error", name: "PositionNotLiquidatable", inputs: [] },
  { type: "error", name: "PrefixLengthExceedsArray", inputs: [] },
  { type: "error", name: "ProfitLowerboundNotReached", inputs: [] },
  { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
  { type: "error", name: "RepaymentWouldRestoreZeroShares", inputs: [] },
  { type: "error", name: "ReserveExists", inputs: [] },
  { type: "error", name: "ReserveFrozen", inputs: [] },
  { type: "error", name: "ReserveNotBorrowable", inputs: [] },
  { type: "error", name: "ReserveNotBorrowed", inputs: [] },
  { type: "error", name: "ReserveNotEnabledAsCollateral", inputs: [] },
  { type: "error", name: "ReserveNotListed", inputs: [] },
  { type: "error", name: "ReserveNotSupplied", inputs: [] },
  { type: "error", name: "ReservePaused", inputs: [] },
  {
    type: "error",
    name: "SafeCastOverflowedIntDowncast",
    inputs: [
      { name: "bits", type: "uint8" },
      { name: "value", type: "int256" },
    ],
  },
  {
    type: "error",
    name: "SafeCastOverflowedIntToUint",
    inputs: [{ name: "value", type: "int256" }],
  },
  {
    type: "error",
    name: "SafeCastOverflowedUintDowncast",
    inputs: [
      { name: "bits", type: "uint8" },
      { name: "value", type: "uint256" },
    ],
  },
  {
    type: "error",
    name: "SafeCastOverflowedUintToInt",
    inputs: [{ name: "value", type: "uint256" }],
  },
  { type: "error", name: "SafeERC20FailedOperation", inputs: [{ name: "token", type: "address" }] },
  { type: "error", name: "SelfLiquidation", inputs: [] },
  { type: "error", name: "SharesRestoredMismatch", inputs: [] },
  {
    type: "error",
    name: "SlippageExceeded",
    inputs: [
      { name: "minOut", type: "uint256" },
      { name: "actualOut", type: "uint256" },
    ],
  },
  { type: "error", name: "StringTooLong", inputs: [{ name: "str", type: "string" }] },
  { type: "error", name: "TBV_AlreadyFrozen", inputs: [] },
  { type: "error", name: "TBV_AlreadyPaused", inputs: [] },
  { type: "error", name: "TBV_CannotUnfreezeWhilePaused", inputs: [] },
  { type: "error", name: "TBV_CannotUnpauseWhileFrozen", inputs: [] },
  { type: "error", name: "TBV_Frozen", inputs: [] },
  { type: "error", name: "TBV_NotFrozen", inputs: [] },
  { type: "error", name: "TBV_NotPaused", inputs: [] },
  { type: "error", name: "TBV_Paused", inputs: [] },
  { type: "error", name: "TBV_Unauthorized", inputs: [] },
  { type: "error", name: "Unauthorized", inputs: [] },
  { type: "error", name: "UnauthorizedVaultKeeper", inputs: [] },
  { type: "error", name: "UnsupportedSettlementToken", inputs: [] },
  { type: "error", name: "UUPSUnauthorizedCallContext", inputs: [] },
  {
    type: "error",
    name: "UUPSUnsupportedProxiableUUID",
    inputs: [{ name: "slot", type: "bytes32" }],
  },
  { type: "error", name: "VaultNotAcquirable", inputs: [] },
  { type: "error", name: "VersionAlreadyExists", inputs: [] },
  { type: "error", name: "ZeroAddress", inputs: [] },
  { type: "error", name: "ZeroAmount", inputs: [] },
  { type: "error", name: "ZeroLiquidation", inputs: [] },
] as const;

/** Every error name `protocolErrorsAbi` can decode, as a union. */
export type ProtocolErrorName = (typeof protocolErrorsAbi)[number]["name"];
